export interface ParsedDimensions {
  width: number;
  height: number;
  sqft: number;
  rate: number;
}

export class SquareFootParser {
  /**
   * Parses the work order line item description to extract square footage dimensions.
   * Format generated by WorkOrderService:
   * "Banner (8 x 4 = 32 sqft @ $10/sqft)"
   * 
   * @param description The raw description string
   * @returns ParsedDimensions if successfully parsed, null otherwise
   */
  static parse(description: string): ParsedDimensions | null {
    if (!description || typeof description !== 'string') return null;

    try {
      // Regex looks for: (width x height = sqft sqft @ $rate/sqft)
      // Supports decimals in all numeric fields
      const regex = /\(([\d.]+)\s*x\s*([\d.]+)\s*=\s*([\d.]+)\s*sqft\s*@\s*\$([\d.]+)\/sqft\)/i;
      const match = description.match(regex);

      if (!match) return null;

      const width = parseFloat(match[1]);
      const height = parseFloat(match[2]);
      const sqft = parseFloat(match[3]);
      const rate = parseFloat(match[4]);

      if (isNaN(width) || isNaN(height) || isNaN(sqft) || isNaN(rate)) {
        return null;
      }

      return { width, height, sqft, rate };
    } catch (e) {
      // Fail gracefully on any unexpected errors
      return null;
    }
  }

  /**
   * Helper to determine if a description likely contains SqFt data
   */
  static hasSqFtData(description: string): boolean {
    return description.toLowerCase().includes('sqft');
  }
}
