import {
  Users,
  LayoutDashboard,
  Box,
  FileText,
  CreditCard,
  BookOpen,
  Settings,
  Bell,
  Search,
  Plus,
  Trash,
  Edit,
  MoreVertical,
  X,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  Loader2,
  Phone,
  Mail,
  MapPin,
  DollarSign,
  Package,
  Wallet,
  TrendingUp,
  BarChart,
  type LucideIcon
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  loader: Loader2,
  phone: Phone,
  email: Mail,
  location: MapPin,
  dashboard: LayoutDashboard,
  customer: Users,
  inventory: Box,
  workOrder: FileText,
  payment: CreditCard,
  ledger: BookOpen,
  report: FileText,
  invoice: FileText,
  settings: Settings,
  notification: Bell,
  search: Search,
  add: Plus,
  delete: Trash,
  edit: Edit,
  more: MoreVertical,
  close: X,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  dollar: DollarSign,
  package: Package,
  wallet: Wallet,
  trend: TrendingUp,
  chart: BarChart,
};
